name: medpia_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  add_to_cart_animation: ^2.0.4
  awesome_snackbar_content: ^0.1.4
  custom_refresh_indicator: ^4.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  hugeicons: ^0.0.7
  intl: ^0.19.0
  infinite_scroll_pagination: ^3.1.0
  mobile_scanner: ^6.0.2
  image: ^4.3.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
